### PR TITLE
Update 02-modules.md

### PR DESCRIPTION
**Pull request by sarahnp7**

### CODE REVIEW

**Comment by sarahnp7** [comment]
Line 809:   "Task: Server an HTML page from S3:"

- I believe Server is not a verb, I've also made a little research. I'd highly suggest using "manage"

Line 675 and 677:   "register **instances** with the load balancer."

registers(this verb) refers to the Classic Load Balancer so we should use the singular verb agreement.

**Review by sarahnp7 — COMMENTED** [review]
- Line 809:   "Task: Server an HTML page from S3:"

I believe Server is not a verb, I've also made a little research. I'd highly suggest using "manage"

- Line 675 and 677:   "register **instances** with the load balancer."

registers(this verb) refers to the Classic Load Balancer so we should use the singular verb agreement. 

- Line 397: 
<http://PUBLIC_URL/> or <http://PUBLIC_URL/index.php>
<http://PUBLIC_URL/phpinfo.php>

These are not working, these are just sample websites right?

- Line 284: Sorry about this, I didn't edit it but I might have clicked on "enter" while reading.

-|**us-west-1**|**US West (N. California)** 👈 *USE THIS FOR LABS*|

- Line 845 should still be- (N. California) region, as an example

**Comment by azat-co** [comment]
@sarahnp7 

1. Yes. The right word is "Serve" in this case
2. It's developers who register
3. Yes. Those URLs are templates in which students need to replace PUBLIC_URL with their URLs
4. I changed it back. You can press command+z to undo in the Github web editor

**Comment by sarahnp7** [comment]
@azat-co 
Okay with those comments :)
command+z - I know this shortcut but I mentioned that there because I've already submitted the pull request when I saw it.

**Pull request merged**
